// Generated by components discovery
declare module 'vue' {
  export interface GlobalComponents {
    'CatalogueSection': typeof import("../components/CatalogueSection/CatalogueSection.vue")['default'],
    'DesktopNavigation': typeof import("../components/DesktopNavigation/DesktopNavigation.vue")['default'],
    'HomepageHero': typeof import("../components/HomepageHero/HomepageHero.vue")['default'],
    'NavigationItem': typeof import("../components/NavigationItem/NavigationItem.vue")['default'],
    'MobileNavigation': typeof import("../components/MobileNavigation/MobileNavigation.vue")['default'],
    'NewsSection': typeof import("../components/NewsSection/NewsSection.vue")['default'],
    'PostComponent': typeof import("../components/PostComponent/PostComponent.vue")['default'],
    'ProductCard': typeof import("../components/ProductCard/ProductCard.vue")['default'],
    'StoreFeature': typeof import("../components/StoreFeature/StoreFeature.vue")['default'],
    'TheFooter': typeof import("../components/TheFooter/TheFooter.vue")['default'],
    'TheHeader': typeof import("../components/TheHeader/TheHeader.vue")['default'],
    'NuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyCatalogueSection': typeof import("../components/CatalogueSection/CatalogueSection.vue")['default'],
    'LazyDesktopNavigation': typeof import("../components/DesktopNavigation/DesktopNavigation.vue")['default'],
    'LazyHomepageHero': typeof import("../components/HomepageHero/HomepageHero.vue")['default'],
    'LazyNavigationItem': typeof import("../components/NavigationItem/NavigationItem.vue")['default'],
    'LazyMobileNavigation': typeof import("../components/MobileNavigation/MobileNavigation.vue")['default'],
    'LazyNewsSection': typeof import("../components/NewsSection/NewsSection.vue")['default'],
    'LazyPostComponent': typeof import("../components/PostComponent/PostComponent.vue")['default'],
    'LazyProductCard': typeof import("../components/ProductCard/ProductCard.vue")['default'],
    'LazyStoreFeature': typeof import("../components/StoreFeature/StoreFeature.vue")['default'],
    'LazyTheFooter': typeof import("../components/TheFooter/TheFooter.vue")['default'],
    'LazyTheHeader': typeof import("../components/TheHeader/TheHeader.vue")['default'],
    'LazyNuxtWelcome': typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default'],
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/layout")['default'],
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default'],
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default'],
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default'],
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default'],
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
  }
}
export const CatalogueSection: typeof import("../components/CatalogueSection/CatalogueSection.vue")['default']
export const DesktopNavigation: typeof import("../components/DesktopNavigation/DesktopNavigation.vue")['default']
export const HomepageHero: typeof import("../components/HomepageHero/HomepageHero.vue")['default']
export const NavigationItem: typeof import("../components/NavigationItem/NavigationItem.vue")['default']
export const MobileNavigation: typeof import("../components/MobileNavigation/MobileNavigation.vue")['default']
export const NewsSection: typeof import("../components/NewsSection/NewsSection.vue")['default']
export const PostComponent: typeof import("../components/PostComponent/PostComponent.vue")['default']
export const ProductCard: typeof import("../components/ProductCard/ProductCard.vue")['default']
export const StoreFeature: typeof import("../components/StoreFeature/StoreFeature.vue")['default']
export const TheFooter: typeof import("../components/TheFooter/TheFooter.vue")['default']
export const TheHeader: typeof import("../components/TheHeader/TheHeader.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyCatalogueSection: typeof import("../components/CatalogueSection/CatalogueSection.vue")['default']
export const LazyDesktopNavigation: typeof import("../components/DesktopNavigation/DesktopNavigation.vue")['default']
export const LazyHomepageHero: typeof import("../components/HomepageHero/HomepageHero.vue")['default']
export const LazyNavigationItem: typeof import("../components/NavigationItem/NavigationItem.vue")['default']
export const LazyMobileNavigation: typeof import("../components/MobileNavigation/MobileNavigation.vue")['default']
export const LazyNewsSection: typeof import("../components/NewsSection/NewsSection.vue")['default']
export const LazyPostComponent: typeof import("../components/PostComponent/PostComponent.vue")['default']
export const LazyProductCard: typeof import("../components/ProductCard/ProductCard.vue")['default']
export const LazyStoreFeature: typeof import("../components/StoreFeature/StoreFeature.vue")['default']
export const LazyTheFooter: typeof import("../components/TheFooter/TheFooter.vue")['default']
export const LazyTheHeader: typeof import("../components/TheHeader/TheHeader.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/@nuxt/ui-templates/dist/templates/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const componentNames: string[]
